INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CHANNELSOUND channelsound)

FIND_PATH(
    CHANNELSOUND_INCLUDE_DIRS
    NAMES channelsound/api.h
    HINTS $ENV{CHANNELSOUND_DIR}/include
        ${PC_CHANNELSOUND_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CHANNELSOUND_LIBRARIES
    NAMES gnuradio-channelsound
    HINTS $ENV{CHANNELSOUND_DIR}/lib
        ${PC_CHANNELSOUND_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CHANNELSOUND DEFAULT_MSG CHANNELSOUND_LIBRARIES CHANNELSOUND_INCLUDE_DIRS)
MARK_AS_ADVANCED(CHANNELSOUND_LIBRARIES CHANNELSOUND_INCLUDE_DIRS)

